annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
pdf:
    resource: "@PdfBundle/Resources/config/routing.yml"
    prefix:   /pdf

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



